server:
  port: 9999
########数据源##############
spring:
  security:
    user:
      name: admin
      password: 123
      roles: admin,employee
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.247:3309/xliot_notifier?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true
    username: hxtech
    password: hxtech@2020
    druid:
      initialSize: 3
      minIdle: 2
      maxActive: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
########MyBatis##############
mybatis:
  type-aliases-package: com.sourcecode.springboot.tomcatwar.dao
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30
########MyProperties#########
my:
  name: wangwei
  age: 18
########Log#########
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG
    org.springframework.security: DEBUG